describe('visitar aesop', () => {
    it('passes', () => {
      cy.visit('https://www.aesop.com.br')
      cy.get('a').contains('Cadastrar-se').click({ force: true })
      cy.get('a').contains('Cadastrar-se').click({ force: true })
      cy.get('input[name="firstName"]').type('Ana Luiza')
      cy.get('input[name="lastName"]').type('Silva Nascimento')
      cy.get('input[name="email"]').type('analuizanascimento2@hotmail.com')
      cy.get('input[name="password"]').type('MinhaSenha!123')
      cy.get('input[name="confirmPassword"]').type('MinhaSenha!123')
      cy.get('input[name="cpf"]').type('840.898.329-69')
      cy.get('input[name="gender"][value="female"]').check({ force: true })
      cy.get('input[name="dateOfBirth"]').type('15/02/1998')
      cy.get('input[name="homePhone"]').type('(11)92345-6789') 
      cy.get('input[name="receiveNewsLetter"]').check({ force: true })
      cy.get('input[name="infContOptIn"]').check({ force: true })
      cy.get('input[name="acceptedterms"]').check({ force: true })
      cy.get('span').contains('Criar Conta').click({ force: true })
          })
  })