 describe('visitar natura', () => {
  it('passes', () => {
    cy.visit('https://www.natura.com.br')
    cy.get('button[class="MuiButtonBase-root MuiIconButton-root MuiIconButton-colorInherit MuiIconButton-edgeStart"').click({ force: true })
    cy.get('a').contains('Cadastrar-se').click({ force: true })
    cy.get('input[name="firstName"]').type('Luiz Walter')
    cy.get('input[name="lastName"]').type('Silva')
    cy.get('input[name="email"]').type('luizwaltersilvas@hotmail.com')
    cy.get('input[name="receiveNewsLetter"]').check({ force: true })
    cy.get('input[name="password"]').type('MinhaSenha!123')
    cy.get('input[name="confirmPassword"]').type('MinhaSenha!123')
    cy.get('input[name="cpf"]').type('677.548.497-63')
    cy.get('input[name="dateOfBirth"]').type('15/02/1998')
    cy.get('input[name="gender"][value="male"]').check({ force: true })
    cy.get('input[name="receiveNewsLetterSms"]').check({ force: true })
    cy.get('input[name="homePhone"]').type('(11)92345-6789')
    cy.get('input[name="pushOptInWP"]').check({ force: true })
    cy.get('input[name="whatsappPhone"]').type('(11)97654-3210')
    cy.get('input[name="infContOptIn"]').check({ force: true })
    cy.get('input[name="acceptedterms"]').check({ force: true })
    cy.get('span').contains('Criar Conta').click({ force: true })
  })
})